from typing import Literal, Optional
from datetime import datetime
from decimal import Decimal
from pydantic import BaseModel, ConfigDict


class ReceiptRead(BaseModel):
    """
    No ReceiptCreate here — a receipt is generated internally by
    payment_service.py in the same transaction as the payment it
    belongs to (1:1, enforced by the unique key on payment_id), never
    submitted directly through the API.

    receipt_number is a human-facing identifier (e.g. printed/shared
    with the buyer or supplier) — generated by the service layer at
    creation time. Exact format (sequence, prefix, per-agent numbering,
    etc.) isn't defined by the schema and needs deciding in
    receipt_service.py.
    """
    model_config = ConfigDict(from_attributes=True)

    receipt_id: int
    receipt_number: str
    payment_id: int
    amount: Decimal
    description: Optional[str] = None
    issued_at: datetime
    created_by: int

    # Populated by the service layer joining payments -> accounts, for
    # AgentReceipts.jsx without extra frontend lookups.
    owner_name: Optional[str] = None
    owner_type: Optional[Literal["buyer", "supplier"]] = None
    agent_name: Optional[str] = None